// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/mediaintel-ui/OptionA.tsx": () => import("../components/mockups/mediaintel-ui/OptionA.tsx"),
  "./components/mockups/mediaintel-ui/OptionB.tsx": () => import("../components/mockups/mediaintel-ui/OptionB.tsx"),
  "./components/mockups/mediaintel-ui/OptionC.tsx": () => import("../components/mockups/mediaintel-ui/OptionC.tsx"),
  "./components/mockups/mobile/CurrentLayout.tsx": () => import("../components/mockups/mobile/CurrentLayout.tsx"),
  "./components/mockups/mobile/MobileRedesign.tsx": () => import("../components/mockups/mobile/MobileRedesign.tsx")
};
